-- KEYCLOAK
CREATE DATABASE IF NOT EXISTS `keycloak` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ACCOUNT_SERVICE
CREATE DATABASE IF NOT EXISTS `accountservice` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ATTEMPT_SERVICE
CREATE DATABASE IF NOT EXISTS `attemptservice` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- TEST_SERVICE
CREATE DATABASE IF NOT EXISTS `testservice` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- COMMENT_SERVICE
CREATE DATABASE IF NOT EXISTS `commentservice` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CHATBOT
CREATE DATABASE IF NOT EXISTS `chatbot` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- NOTIFICATION_SERVICE
CREATE DATABASE IF NOT EXISTS `notificationservice` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';